name: Synthetic Test
on:
  push:
    branches:
    - "**"
    - "!main"

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: "16"
    - name: Test
      run: yarn ci:install && yarn ci:test
